### ISSUE TITLE
error when running olps

### ISSUE THREAD

**Issue by mmayo888** [OLPS/OLPS#1]
Hi there,

I am trying to run the current version of OLPS on a Max OS X 10.10.2 PC with GNU Octave 3.8.0. Currently I get an error when I try run the OLPS_cli script. Here is the error:

```
octave:2> cd OLPS/
octave:3> OLPS_cli.m 
----Begin ubah on djia-----
-------------------------------------
Market(tc=0.0000), Cumulative return: 0.76
-------------------------------------
----End ubah on djia-----
error: save: unable to open output file '../Log/Mat/ubah-djia-2015-0220-11-27.mat'
error: called from:
error:   /Users/mmayo/OLPS/Strategy/manager.m at line 105, column 5
error:   /Users/mmayo/OLPS/OLPS_cli.m at line 36, column 1
octave:3> 
```

Thanks
Mike

**Comment by binliwhu** [comment]
Thanks for the issue. 

We have missed a directory (Mat) when submitting the code. The bug is solved. Please use the latest version.
