### ISSUE TITLE
Transaction cost optimization for online portfolio selection

### ISSUE THREAD

**Issue by akaniklaus** [OLPS/OLPS#3]
Implementation of the following recent strategy ("Transaction cost optimization for online portfolio selection") is missing from the framework, I would be glad if someone can implement this as well:
http://ink.library.smu.edu.sg/cgi/viewcontent.cgi?article=4761&context=sis_research

**Comment by binliwhu** [comment]
I will try to update within this week.

**Comment by akaniklaus** [comment]
Thanks!

**Comment by uramoon** [comment]
Could you upload the implementations of TCO strategies? I personally implemented the strategies, however, the results were different from the paper published in Quantitative Finance.

**Comment by akaniklaus** [comment]
@uramoon This is what Mr. Li previously shared with me.
[TCO.zip](https://github.com/OLPS/OLPS/files/2612589/TCO.zip)

**Comment by uramoon** [comment]
Thank you very much. I really appreciate it.
