### ISSUE TITLE
2016 Matlab version not supported OLPS

### ISSUE THREAD

**Issue by Nosherwan77** [OLPS/OLPS#4]
I have install 2016 version of MATLAB, but when i run and  want to add my data file in configuration setting . the option of Data-"Add data" are shown disable. So, i can not add my data file for algorithm analysis. I did not face this problem in 2008 or 2013 version. Is their any solution for 2016 version? I attached the file for convenience 
[configuratiion.docx](https://github.com/OLPS/OLPS/files/1848123/configuratiion.docx)

**Comment by doyensahoo** [comment]
Thanks Nosherwan.

We may not have access to Matlab 2016 at the moment. 

How about trying the same thing via the Pseudo-GUI? It is essentially the same as the GUI (with a menu driven interface). It might at least address the data adding problem - and for other stuff you can use the original GUI.
