### ISSUE TITLE
Adding New Data Sets

### ISSUE THREAD

**Issue by bhuvanmittal** [OLPS/OLPS#5]
In the OLPS toolbox manual, in the "Adding new Dataset" Section it is written: "A dataset is in the form of **price relative vectors of various assets**. The t th row represents the price relative of all the assets at time t. The user just has to save the new price relative matrix in the Data folder"
How I can calculate price relative vectors. What is the mathematical formula to calculate it?

**Comment by doyensahoo** [comment]
Let price at t = 1, 2,... be p1, p2, ... of a particular asset. 

Price relative at t = 1 is not available. 
Price relative at t = 2 for this asset will be p2/p1. 
Price relative at t = 3 for this asset will be p3/p2. 
...

See Introduction, 1.1. in the manual for more details. 
https://github.com/OLPS/OLPS/blob/master/Documentation/OLPS_manual.pdf
