### ISSUE TITLE
Code change to lessen computation time

### ISSUE THREAD

**Issue by Auxiliumdesign** [OLPS/OLPS#9]
I've noticed that the code in PAMR, and other strategies that are only using a one or a small amount of previous data, is still reading all data in the weight method.

        [day_weight] = pamr_kernel(data(1:t-1, :), day_weight, eta);

Which take all rows between the first and t-1th. This is alright for the smaller data-sets, but for the larger NYSE dataset, lot's of time can be saved. 

I see no reason why the code couldn't be 

        [day_weight] = pamr_kernel(data(t-1, :), day_weight, eta);

reading an Array of m objects, instead of n*m. I also can't see this effecting any other calculation.

Similar things can be done for CWMR and Olmar if I am not mistaken, but there utilize the windowsize to determine how many objects to copy.

When running NYSE on my computer I went from 9 seconds to 3 seconds in computational time with this change, and getting the same results.

**Comment by Auxiliumdesign** [comment]
Pre change

NYSE(O)
PAMR    (0.50, 0.0000), Final return: 5138427764160573.00
PAMR-1(epsilon:0.50, C:500, tc:0.0000), Final return: 5138427764160573.00
PAMR-2(epsilon:0.50, C:500, tc:0.0000), Final return: 4875047263119554.00
CWMR-Stdev(2.00, 0.50, 0.0000), Final return: 6485692778698332.00
CWMR-Var(2.00, 0.50, 0.0000), Final return: 6513647545037656.00
Elapsed time is 38.61 seconds.

After change
NYSE(O)
PAMR    (0.50, 0.0000), Final return: 5138427764160573.00
PAMR-1(epsilon:0.50, C:500, tc:0.0000), Final return: 5138427764160573.00
PAMR-2(epsilon:0.50, C:500, tc:0.0000), Final return: 4875047263119554.00
CWMR-Stdev(2.00, 0.50, 0.0000), Final return: 6485692778698332.00
CWMR-Var(2.00, 0.50, 0.0000), Final return: 6513647545037656.00
Elapsed time is 17.92 seconds.

**Comment by binliwhu** [comment]
Hi,

PAMR calculates next weight using only t-1’s price relative. So even you pass 1:t-1’s price relatives to the kernel function, it only utilizes the t-1’s price relative. The time cost shortens may be Matlab optimization the parameter (1:t-1’s price matrix) by buffering(unconfirmed). 

Best,
Bin

发自我的 iPhone

**Comment by Auxiliumdesign** [comment]
Exactly, I thought it would be something like that. I am just glad that I speed up my calculations.
